### PR TITLE
#75 resolved

### PR DESCRIPTION
**Pull request by khushimarothi**
I have updated the readme by adding the badges , also added a table for project maintainers, a contributors section and some emojis that will catch reader eyes. Tried to solved #75 issue. Hope you like the changes and any kind of remarks or changes are welcomed.
also your repo is not having MIT license so kindly add it otherwise the badge of ""License" will stay showing not specified.

### CODE REVIEW

**Comment by SiddhantPawar03** [comment]
Hey @khushimarothi great work!
Could you work on few changes:
1) Check the alignment for bullet points.
2) Also add github id of PA
https://github.com/Pavan49719
https://github.com/SiddhantPawar03
3) Also add hackclub rait logo mentioning about participation.......

**Comment by khushimarothi** [comment]
1. I will do it.
2.  Just click on the images of the admin . You will reach on the github account.  If that's not fine will try to add logo of github than link the id.
3. Okay.

**Comment by khushimarothi** [comment]
@SiddhantPawar03  I did all the suggested changes. Also I added github logo with links and the images will too lead directly into github.

**Comment by SiddhantPawar03** [comment]
Great Work @khushimarothi !
PR Approved!
Keep Contributing!

**Comment by khushimarothi** [comment]
> Great Work @khushimarothi ! PR Approved! Keep Contributing!

Thank you😄

**Pull request merged**
