### PR TITLE
login screen

### PR DESCRIPTION
**Pull request by Maruti54**
## Related Issue 

- Info about the related issue 

- [x] HSOC Participant   
- [x] Contributor

Closes: #5

### Describe the changes you've made

Login Screen has been added with functionality to accept email and passwords (in obsecure manner). Also, the forgot password button has been added. And Additional login platform buttons have been added.
Along with the functionalities, one gets an enhanced user experience with interactive UI.
I have also used the declared text controllers.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing?

I have enclosed the screenshots of the template.

Password Visible | Password Invisible
:-------------------------:|:-------------------------:
image | image

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Maruti54** [comment]
@SiddhantPawar03 
I have made changes in this PR

**Review by Pavan49719 — COMMENTED** [review]
Great work @Maruti54 !!
@SiddhantPawar03 Ready to merge.

**Comment by SiddhantPawar03** [comment]
> @SiddhantPawar03 I have made changes in this PR

PR Approved! Great Work @Maruti54 👌

**Comment by Maruti54** [comment]
Thank you @Pavan49719  and @SiddhantPawar03 , it was comfortable to work on it as the issue was explained in detail and also code hierarchy is maintained systematically.

**Pull request merged**
